### ISSUE TITLE
Question: Why double quotes for attributes?

### ISSUE THREAD

**Issue by mmzoo** [idmean/slim-style-guide#1]
Hi, I really like your style guide. I've been looking for a slim linter for quite some time and a style guide is a good start :)

What are your thoughts on "Prefer double quotes for quoted attributes"?

Technically, everything after the `=` is ruby, so maybe it should be aligned with the ruby style guide there? It [allows both](https://github.com/bbatsov/ruby-style-guide#consistent-string-literals) as long as it's consistent.

Personally I'm a fan of the mentioned Option A). That is, use double quotes if you want to interpolate. Use single if you want to visually highlight that there is not going to be any interpolation in that string.

**Comment by idmean** [comment]
Interesting point. My initial thoughts on this were that I wanted the code to look as similar to HTML as possible while keeping alle the shortness and coolness of Slim that we love. 
Also, I think string interpolation for quoted attributes is rare. I can’t think of any examples except for some dynamic `style` things, but the `style` attribute isn’t nice anyway.

I also prefer option A for Ruby code but I feel different for Slim code. Maybe we could add options here?

**Comment by mmzoo** [comment]
> My initial thoughts on this were that I wanted the code to look as similar to HTML as possible

That's what I guessed. And I tend to agree. Yet usually I see it as Ruby in my head and I'm automatically thinking "these semantics tell me that it's not just a dumb string, it's a string that is to be interpolated".

> Also, I think string interpolation for quoted attributes is rare. [...] I can’t think of any examples except for some dynamic style things

I first thought, "what does he mean? They are all over the place!" And then I went through the views of a big project just to see that you are rather right. In every third partial there is maybe one interpolation. Those are, however, pretty legitimate cases:

```slim
# Javascript-related stuff
span data-tooltip="this-needs-to-match-another-dynamic-#{record.id}"

# This could be avoided by using the `active_link_to` gem
# But it still feels like a common enough use case.
div class="toggle-favorite #{'active' if record.favorite?}"

# Could this maybe be avoided by passing in a Ruby Array?
# I haven't tried it. Otherwise I don't see how to avoid it.
span class="product product-status-#{product.state}"

# This it's arguably more ruby-like than HTML-like
# Could be avoided though with some effort
ul class=('inline-list' if @something)

# Or even this. We try to avoid it because it's not intuitive.
# But I must say I like the syntax highlighting in my editor (Symbol vs String)
div class=(:hoverable if @something)

# By the way, what's your take on this? Quote Integers or not?
div data-position=5
div data-position=record.position
```

> Maybe we could add options here?

I guess my summary is this: I'm okay with using double-quotes when the String contains just a word or two. But when I have to use interpolation alongside, then I slowly start feeling uncomfortable with the semantics.

> I already planed to look into this but I haven’t had the time yet.

🐇 🍪 🍇 🐈 🆕 😄

**Comment by idmean** [comment]
These are good examples. While I agree that interpolation for JavaScript is sometimes necessary, it can actually be avoided by good design. I also prefer 

```slim
ul class=('inline-list' if @something)
/ Your second example
.toggle-favorite class=('active' if record.favorite?) 
```

whenever possible. Nonetheless, I like your solution. Do you want to make a pull request to include it?

**Comment by mmzoo** [comment]
Look [at that](https://github.com/sds/slim-lint). That thing was created 2 years ago, how could I not have found it? Going to try it out...

**Comment by idmean** [comment]
Cool! I haven’t seen that either. I’ll definitely give it a try.
